### ISSUE TITLE
suggestion: add nette.ajax.js

### ISSUE THREAD

**Issue by klimesf** [nette/sandbox#62]
AJAX, as in [documentation](http://doc.nette.org/cs/2.2/ajax), is not fully functional in sandbox.
I suggest adding [nette.ajax.js](https://github.com/vojtech-dobes/nette.ajax.js) to the `/www/js` folder, linking the file and adding

``` js
$(function () {
    $.nette.init();
});
```

to `app/@layout.latte`

**Comment by JanTvrdik** [comment]
I'm against because it depends on jQuery.

**Comment by klimesf** [comment]
Well, jQuery is already included

**Comment by JanTvrdik** [comment]
Maybe it should not be included. Unexperienced user may use it in production even though it may be

**Comment by klimesf** [comment]
Okay, so change is needed either way.
I suggest adding warning to documentation and adding `nette.ajax.js`.
Or, by this logic, `/www/js/jquery.js` should be removed.

**Comment by dg** [comment]
jQuery is special, it is used on nearly ever second website (http://trends.builtwith.com/javascript/jQuery).

**Comment by JanTvrdik** [comment]
@dg Yes, that is a known fact. The question is – should Nette encourage people to use it or not? Are you not afraid that people may accidentally use the non-minimized version of jQuery in production?

I personally think that Nette should stay neutral regarding jQuery, e.g. not include in sandbox.

**Comment by klimesf** [comment]
@JanTvrdik The main reason why I'm bringing this suggestion up is that it's easier for beginners this way. Having jQuery and nette.ajax.js included makes AJAX work right away - less frustration using Nette.

Friends of mine were programming their semestral projects in Nette on my recommendation and gave me this feedback.

Experienced users can always minimize or unlink the files. In my opinion, warning in documentation is sufficient.

**Comment by fprochazka** [comment]
I think it should be in sandbox even for the cost the begginer might use it non-minimized. Who cares? Is a begginer gonna create a new facebook? I don't think so. And even if - he can always optimize later.

**Comment by fprochazka** [comment]
I would be in favor of writing a tutorial how to start with bower and nette and then we might consider removing it from sandbox and replacing it with bower.json or whatever is the dependencies file for bower.

**Comment by klimesf** [comment]
@fprochazka great idea :+1:

**Comment by klimesf** [comment]
@JanTvrdik Actually, even if you don't include jQuery in sandbox, unexperienced user can still include it in non-minified version on his own. We can't prevent it this way.

**Comment by dg** [comment]
btw #53

**Comment by JanTvrdik** [comment]
> replacing it with bower.json

The trouble I have with bower is that it is not a (de facto) standard. The frontend world is much more unstable than backend with Composer. Also last time I tried bower it was pretty bad experience. The tool was way less usable than Composer. Not sure whether it changed.

> unexperienced user can still include it in non-minified version on his own. 

That seems unlikely, users tend to download the first link available. And also – that is not really our problem.

**Comment by dg** [comment]
@JanTvrdik I agree that bower is immature, so current solution (jQuery in sandbox) is the best for beginners. I didn't know that there is non-minified version, it is probably mistake.

**Comment by klimesf** [comment]
So, if the jQuery is included in minified version, are there any other objections against including nette.ajax.js?

**Comment by dg** [comment]
Yes, someone will have to update it etc.

**Comment by JanTvrdik** [comment]
With what extensions available and what extensions enabled by default?

**Comment by klimesf** [comment]
@dg Yes, that is a problem, howerer jQuery needs to be updated aswell.

@JanTvrdik Having Snippets and Init by default is reasonable in my opinion (as they are used in the tutorial), Redirect could be enabled by default aswell.
Why not having all extensions available?

**Comment by fprochazka** [comment]
Btw, we might create a post install to composer hook that will automagically download the latest versions of both libs.

**Comment by dg** [comment]
In the first place, the documentation is wrong. Documentation must not depend on 3rdparty plugins. The warning „To make AJAX work you need to include nette.ajax.js library by Vojtěch Dobeš.“ is wrong too, because it is simply not right. You need only IE5+ browser to make AJAX work.

So leave sandbox as is and fix documentation.

**Comment by klimesf** [comment]
@dg I added this warning to the documentation yesterday. The tutorial is using class="ajax" and is not describing the JS implementation, which is proved misleading for the beginners. Hence the warning.

**Comment by dg** [comment]
I understand, but it is just workaround, because it creates a false impression about Nette & AJAX.

**Comment by klimesf** [comment]
Okay, I will create PR.

Btw do we have any statistics about ajax.nette.js usage in projects using Nette? If it's  Doesn't it classify for including by the same logic jQuery does?

**Comment by vojtech-dobes** [comment]
I have 2 questions:

1. Should `nette.ajax.js` become part of Nette Framework itself?
2. Is that possible/good thing if it depends on jQuery?

I would answer both questions with yes:

1. Because it makes Ajax ready for beginners immediatelly, and solves a lot of beginner problems for them ("after ajax request my shining button stops working").
2. Yeah - if somebody doesn't use jQuery, he's not beginner and `nette.ajax.js` will probably won't bring so much goodness for him.

I am unsure whether `nette.ajax.js` isn't too opinionated to become part of framework.

And still, it should remain clear anywhere, that server and client can always be used in decoupled way, and `nette.ajax.js` is just an option.

**Comment by klimesf** [comment]
I completely agree with @vojtech-dobes.

Based on nature of Nette, sandbox should
a) be begginer friendly
b) support rapid development
which are the main reasons why I think adding nette.ajax.js is a good idea.

Experts can always opt for lightweight version of the sandbox.

**Comment by JanTvrdik** [comment]
@vojtech-dobes I'll ask one more time – "With what extensions available and what extensions enabled by default?"

**Comment by vojtech-dobes** [comment]
> @vojtech-dobes I'll ask one more time – "With what extensions available and what extensions enabled by default?"

I don't have any special suggestion, so right now I wouldn't change it. Which means these available and enabled by default: `abort`, `unique`, `state`, `redirect`, `snippets`, `forms`, `validation`, `load`, `init` - all these are part of `nette.ajax.js` file.

**Comment by medhi** [comment]
If my opinion matters, I also agree with @vojtech-dobes. This step will take the framework closer to beginners, which is more important than its correctness. 

Or  -- we can have correct framework, which nobody uses.

**Comment by dg** [comment]
It would be good to not mix different things together.

First of all, I think that `nette.ajax.js` is great front-end counterpart for Nette snippets etc. (And probably there is no other library, so `nette.ajax.js` is clearly the best counterpart :-) )

**1) Should nette.ajax.js become part of Nette Framework itself?**

It is really hard to say what is part of Nette Framework (I mean now, since v2.2). So:

**1a) Should nette.ajax.js become part of github.com/nette organization?**

Yes, I'll be glad. In this case I would suggest to consider name of repository, because it is jQuery plugin and it should be noted in its name (like https://github.com/rails/jquery-ujs).

It will still be Vojta's plugin, with all responsibility and all the fame ;)

**1b) Should nette.ajax.js become part of documentation?**

Yes, but again: documentation will be Vojta's responsibility. 

**1c) Should nette.ajax.js become part of sandbox?**

I really don't like current solution, when JS libraries are hard copied into sandbox. The same problem I have with Adminer, so I created [half solution](https://github.com/dg/adminer-custom). And opened #53 to move jQuery & netteForms out of sandbox. But Bower is only "stupid" downloader, [duo](http://duojs.org/) is immature, so this is still opened.

So I am really not big fan to hardcoping nette.ajax.js into sandbox, especially when it has own extensions (the question is which should be enabled etc.).

I am not against it. But I'd rather find another (clean) way.

**Comment by fprochazka** [comment]
:+1: on moving `nette.ajax.js` and `nette.ajax.history.js` to nette github organization.

**Comment by fmasa** [comment]
@dg Wouldn't hosting it somewhere (just like netteForms.js) solve the hardcoding issue until there will be better front end tooling?

**Comment by dg** [comment]
I think this issue is obsolete.
